{{- if .Values.database.postgres.enabled }}
{{- $fullName := include "warden.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}-postgresql
  labels:
    {{- include "warden.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ $fullName }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      {{- include "warden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "warden.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.database.postgres.image.repository }}:{{ .Values.database.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.database.postgres.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.postgres.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "warden.postgresSecretName" . }}
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.database.postgres.auth.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.database.postgres.resources | nindent 12 }}
      {{- if not .Values.database.postgres.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.database.postgres.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.database.postgres.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.database.postgres.persistence.size }}
        {{- if .Values.database.postgres.persistence.storageClass }}
        storageClassName: {{ .Values.database.postgres.persistence.storageClass | quote }}
        {{- end }}
  {{- end }}
{{- end }}
