{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clustercost-agent-k8s.serviceAccountName" . }}
  labels:
    {{- include "clustercost-agent-k8s.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clustercost-agent-k8s.fullname" . }}
  labels:
    {{- include "clustercost-agent-k8s.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clustercost-agent-k8s.fullname" . }}
  labels:
    {{- include "clustercost-agent-k8s.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clustercost-agent-k8s.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "clustercost-agent-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
