{{- if and .Values.remote.enabled .Values.remote.authTokenSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.remote.authTokenSecret.name }}
  labels:
    {{- include "clustercost-agent-k8s.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  {{ .Values.remote.authTokenSecret.key }}: {{ .Values.remote.authTokenSecret.value | quote }}
{{- end }}
