{{- if .Values.metricsServiceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "clustercost-agent-k8s.fullname" . }}
  labels:
    {{- include "clustercost-agent-k8s.labels" . | nindent 4 }}
    {{- with .Values.metricsServiceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "clustercost-agent-k8s.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ default .Release.Namespace .Values.metricsServiceMonitor.namespace }}
  endpoints:
    - port: http
      interval: {{ .Values.metricsServiceMonitor.interval }}
      path: /metrics
{{- end }}
