apiVersion: v2
name: warden
description: Helm chart for Warden â€” open-source uptime monitoring built in Go
type: application
version: 0.2.2
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/projecthelena/charts/main/assets/icon.png
home: https://github.com/projecthelena/helm-charts
sources:
  - https://github.com/projecthelena/helm-charts
keywords:
  - monitoring
  - uptime
  - status-page
  - kubernetes
maintainers:
  - name: Project Helena
    email: jesus@projecthelena.com
